apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: capstone-cronjob
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scraper
            image: <username>/<image:tag>
            command: ["./scraper.sh"]
          - name: apicall
            image: <username>/<image:tag>
            command: ["./apicall.sh"]
          - name: movesnowflake
            image: <username>/<image:tag>
            command: ["./movesnowflake.sh"]
          restartPolicy: OnFailure