apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:   
      containers:
      - name: scraper
        image: <username>/<image:tag>
        ports:
        - containerPort: 8080
      - name: apicall
        image: <username>/<image:tag>
        ports:
        - containerPort: 8080
      - name: movesnowflake
        image: <username>/<image:tag>
        ports:
        - containerPort: 8080